services:
  ssh-server:
    build: .
    container_name: ssh-client
    ports:
      - "2222:22"  # Exponer el puerto 2222 del host al puerto 22 del contenedor
    volumes:
      - ./.ssh:/.ssh
    networks:
      production_net:
        ipv4_address: 172.30.0.2 
    privileged: true  # Habilitar privilegios adicionales
    command: >
      bash -c "/usr/local/bin/iptables-rules.sh && ip route add 172.40.0.0/24 via 172.30.0.1 && tail -f /dev/null"

networks:
  production_net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.30.0.0/24"

