services:
  ftp:
    container_name: ftp_server
    image: ftp-anon-debian
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    restart: unless-stopped
    networks:
      development_net:
        ipv4_address: 172.40.0.2
networks:
  development_net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.40.0.0/24"